# Generated by Django 5.0.7 on 2024-07-26 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='obrazek',
            field=models.URLField(validators=[django.core.validators.RegexValidator(code='invalid_link', message='Please enter a valid image link.', regex='^https:\\/\\/.+\\.jpg$')]),
        ),
    ]
