# Generated by Django 5.0.7 on 2024-07-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_image_obrazek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
